spring:
  application:
    name: alkywallet

  h2:
    console:
      enabled: true
      path: /h2

  #Conexion a base de datos
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:alkywalletdb
    username: admin
    password:

  jpa:
    database: h2
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true

#Logs para bases de datos
logging:
  level:
    sql: debug